spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id:
                        client-secret:
            resourceserver:
                jwt:
                    issuer-uri: https://accounts.google.com
